# Histogram Specification
### Created By : Pratik Adle (BT17ECE034)

In [18]:
import numpy as np

# Input Image Matrix - 3x3 Matrix
image_matrix = np.array([[1,3,5], [4,4,3], [5,2,2]])
print('Image Matrix is :')
print(image_matrix)

# Target Matrix 
target_matrix = np.array([0,0,0,0,2,2,4,1])
print('\nTarget Matrix is :',target_matrix)

# Gray Level Matrix
gray_level  = np.array([0,1,2,3,4,5,6,7])

# Counting Number of Pixels for each Gray Level
no_of_pixels = np.array([0,0,0,0,0,0,0,0])

for i in range(8):
    no_of_pixels[i] = (image_matrix == i).sum()

print('\nGray Levels   : ',gray_level)
print('No. of Pixels : ',no_of_pixels)



# Calculatig CDF and Equalized Value for Image Matrix
cdf = np.array([0,0,0,0,0,0,0,0])
equalized_value = np.array([0,0,0,0,0,0,0,0])

# CDF calculation
for j in range(8):
    cdf[j] = no_of_pixels[j] + cdf[j-1]
    
print('\nCDF :',cdf)

# Total
total = cdf[7]

# Equalized Value Calculation 
# Equalized Value = (CDF/Total)*(L-1)
# Here L=8 
for k in range(8):
    equalized_value[k] = round((cdf[k]/total)*7)
print('\nEqualized Value for Image :',equalized_value)

Image Matrix is :
[[1 3 5]
 [4 4 3]
 [5 2 2]]

Target Matrix is : [0 0 0 0 2 2 4 1]

Gray Levels   :  [0 1 2 3 4 5 6 7]
No. of Pixels :  [0 1 2 2 2 2 0 0]

CDF : [0 1 3 5 7 9 9 9]

Equalized Value for Image : [0 1 2 4 5 7 7 7]


In [26]:
# Writing all input parameters together
print('\n              Gray Levels : ',gray_level)
print('            No. of Pixels : ',no_of_pixels)
print('            CDF for Image : ',cdf)
print('Equalized Value for Image : ',equalized_value)


              Gray Levels :  [0 1 2 3 4 5 6 7]
            No. of Pixels :  [0 1 2 2 2 2 0 0]
            CDF for Image :  [0 1 3 5 7 9 9 9]
Equalized Value for Image :  [0 1 2 4 5 7 7 7]


In [31]:
# For Target Matrix
target_value_pixel = np.array([0,0,0,0,0,0,0,0])
target_cdf = np.array([0,0,0,0,0,0,0,0])
target_equalized_value = np.array([0,0,0,0,0,0,0,0])

print('               Gray Levels : ',gray_level)

# Calculating CDF for Target Matrix
for l in range(8):
    target_cdf[l] = target_matrix[l] + target_cdf[l-1]
print('     CDF for Target Matrix : ',target_cdf)

# Calculating Equalized Value for Target Matrix
for m in range(8):
    target_equalized_value[m] = round((target_cdf[m]/total)*7)
print('Equalized Value for Target : ',target_equalized_value)

               Gray Levels :  [0 1 2 3 4 5 6 7]
     CDF for Target Matrix :  [0 0 0 0 2 4 8 9]
Equalized Value for Target :  [0 0 0 0 2 3 6 7]


In [45]:
# Writing Gray Level, Image and Target Equalized Values together

print('                   Gray Level :',gray_level)
print(' Input Histogram Equalization :', equalized_value)
print('Target Histogram Equalization :', target_equalized_value)

                   Gray Level : [0 1 2 3 4 5 6 7]
 Input Histogram Equalization : [0 1 2 4 5 7 7 7]
Target Histogram Equalization : [0 0 0 0 2 3 6 7]


In [52]:
# Output
print('Output :')

# Mapping 
mapping_matrix = []
for n in equalized_value:
    gray_eq = np.where(target_equalized_value >= n)
    mapping_matrix.append(gray_eq[0][0])

# Print Map Matrix 
mapping_matrix = np.asarray(mapping_matrix)
print('Map :',mapping_matrix)    

Output :
Map : [0 4 4 6 6 7 7 7]


In [55]:
# Writing all parameters together
print('                   Gray Level :',gray_level)
print(' Input Histogram Equalization :', equalized_value)
print('Target Histogram Equalization :', target_equalized_value)
print('                          Map :',mapping_matrix)

                   Gray Level : [0 1 2 3 4 5 6 7]
 Input Histogram Equalization : [0 1 2 4 5 7 7 7]
Target Histogram Equalization : [0 0 0 0 2 3 6 7]
                          Map : [0 4 4 6 6 7 7 7]
